import * as import$react from "react";
import * as import$react_dom from "react-dom";
import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
'use strict';var v8=function(a,b){let c,d;for(let e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(let f=0;f<u8.length;f++)c=u8[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},w8=function(a,b,c){return new $APP.Fo($APP.kp.B(b,$APP.I,$APP.Wo,!0),a,$APP.I.i(c,$APP.Xo,!0))},x8=function(a){return 2>$APP.Xd(a)?$APP.Qm(a):[$APP.Qm($APP.qk.i(a,0,1)),$APP.qk.h(a,1)].join("")},z8=function(a){if("string"===typeof a)return a;a=$APP.ak(a);var b=$APP.Wm.h(a,/-/),c=$APP.u(b);b=$APP.v(c);
c=$APP.w(c);return $APP.p(y8.g?y8.g(b):y8.call(null,b))?a:$APP.Zg.i($APP.r,b,$APP.Dk.h(x8,c))},A8=function(a){var b=function(){var c=function(){var d=$APP.me(a);if(d){d=a.displayName;if($APP.p(d))return d;d=a.name;return"string"===typeof d&&$APP.u(d)?d:null}return d}();if($APP.p(c))return c;c=function(){var d=null!=a?a.J&4096||$APP.od===a.Jd?!0:!1:!1;return d?$APP.ak(a):d}();if($APP.p(c))return c;c=$APP.A(a);return $APP.ze(c)?$APP.O.g(c):null}();return $APP.p(b)?$APP.Om($APP.r.g(b),"$","."):null},
B8=function(a){return a instanceof $APP.sg||a instanceof $APP.t},D8=function(a){if($APP.ze(a))try{var b=$APP.Te.h(a,C8)}catch(c){b=null}else b=null;return b},E8=function(a){var b=C8.g($APP.A(a));if($APP.p(b))return b;b=D8($APP.y.i(a,1,null));if($APP.p(b))return b;b=$APP.y.i(a,0,null);switch(b instanceof $APP.sg?b.Ia:null){case "\x3e":case "f\x3e":return D8($APP.y.i(a,2,null));case "r\x3e":return a=$APP.y.i(a,2,null),null==a?null:a.key;default:return null}},F8=function(a){return setTimeout(a,16)},
G8=function(a,b){return a.Yd-b.Yd},H8=function(){return null},I8=function(a){for(var b=a.length,c=0;;)if(c<b){var d=a[c];d.s?d.s():d.call(null);c+=1}else return null},J8=function(a,b,c){b.push(c);return a.schedule()},K8=function(){this.vd=!1},M8=function(a){if($APP.p(a.cljsIsDirty))return null;a.cljsIsDirty=!0;return L8.queue_render(a)},N8=function(a){if(null!=a&&null!=a.pf)a=a.id;else{var b=N8[$APP.ba(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=N8._,null!=b)a=b.g?b.g(a):b.call(null,
a);else throw $APP.Za("Compiler.get-id",a);}return a},O8=function(a,b,c){if(null!=a&&null!=a.Ie)a=a.Ie(a,b,c);else{var d=O8[$APP.ba(null==a?null:a)];if(null!=d)a=d.i?d.i(a,b,c):d.call(null,a,b,c);else if(d=O8._,null!=d)a=d.i?d.i(a,b,c):d.call(null,a,b,c);else throw $APP.Za("Compiler.parse-tag",a);}return a},P8=function(a,b){if(null!=a&&null!=a.Ge)a=a.Ge(a,b);else{var c=P8[$APP.ba(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=P8._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $APP.Za("Compiler.as-element",
a);}return a},Q8=function(a,b,c,d,e){if(null!=a&&null!=a.He)a=a.He(a,b,c,d,e);else{var f=Q8[$APP.ba(null==a?null:a)];if(null!=f)a=f.G?f.G(a,b,c,d,e):f.call(null,a,b,c,d,e);else if(f=Q8._,null!=f)a=f.G?f.G(a,b,c,d,e):f.call(null,a,b,c,d,e);else throw $APP.Za("Compiler.make-element",a);}return a},S8=function(a,b){b.Bd=null;a:{var c=R8;R8=b;try{var d=a.s?a.s():a.call(null);break a}finally{R8=c}d=void 0}a=b.Bd;b.nc=!1;a:{c=b.yc;var e=null==a?0:a.length,f=e===(null==c?0:c.length);if(f)for(f=0;;){var h=
f===e;if(h){c=h;break a}if(a[f]===c[f])f+=1;else{c=!1;break a}}else c=f}c||b._update_watching(a);return d},T8=function(a){var b=R8;if(null!=b){var c=b.Bd;null==c?b.Bd=[a]:c.push(a)}},U8=function(a,b,c){a.gb=$APP.I.i(a.gb,b,c);return a.he=null},V8=function(a,b){a.gb=$APP.Ln.h(a.gb,b);return a.he=null},W8=function(a,b,c){var d=a.he;d=null==d?a.he=$APP.mf(function(q,k,x){q.push(k);q.push(x);return q},[],a.gb):d;for(var e=d.length,f=0;;)if(f<e){var h=d[f],m=d[f+1];m.B?m.B(h,a,b,c):m.call(null,h,a,b,c);
f=2+f}else break},X8=function(a,b,c,d){$APP.Fc(a,["#object[reagent.ratom.",$APP.r.g(c)," "].join(""));a:{c=R8;R8=null;try{var e=d;break a}finally{R8=c}e=void 0}$APP.Ck(e,a,b);return $APP.Fc(a,"]")},Y8=function(a,b,c,d){this.state=a;this.D=b;this.ge=c;this.gb=d;this.C=2154201088;this.J=114690},Z8=function(a){if(null!=a&&null!=a.ce)a=a.ce(a);else{var b=Z8[$APP.ba(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Z8._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.Za("IDisposable.dispose!",
a);}return a},$8=function(a,b,c,d){return a._handle_change(b,c,d)},a9=function(a){this.f=a;this.state=null;this.nc=!0;this.Ee=!1;this.Cd=this.Mb=this.gb=this.yc=null;this.C=2153807872;this.J=114690},c9=function(){for(;;){var a=b9;if(null==a)return null;b9=null;for(var b=a.length,c=0;;)if(c<b)a[c]._queued_run(),c+=1;else break}},g9=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;c=1<b.length?new $APP.wd(b.slice(1),0,null):null;b=arguments[0];var e=$APP.ah(c);
c=$APP.Te.h(e,d9);d=$APP.Te.h(e,e9);e=$APP.Te.h(e,f9);b=new a9(b);b._set_opts(new $APP.n(null,3,[d9,c,e9,d,f9,e],null));return b},j9=function(a,b){var c=h9,d=i9,e=S8(a,d);null!=d.yc&&(i9=g9(null),d._set_opts(c),d.f=a,d.Mb=function(){return M8.g?M8.g(b):M8.call(null,b)},b.cljsRatom=d);return e},k9=function(a,b){var c=b.argv;if(null==c){c=$APP.H;a=a.constructor;a:for(var d=$APP.ka(b),e=d.length,f=$APP.fh,h=0;;)if(h<e){var m=d[h];f=$APP.I.i(f,$APP.Ek.g(m),$APP.ma(b,m));h+=1}else break a;b=new $APP.G(null,
2,5,c,[a,f],null)}else b=c;return b},l9=function(a){var b;if(b=$APP.me(a))a=null==a?null:a.prototype,b=null!=(null==a?null:a.pc);return b},m9=function(a,b){for(;;){var c=a.pc,d=!0===a.bf?c.call(a,a):function(){var e=k9(a,a.props);switch($APP.Xd(e)){case 1:return c.call(a);case 2:return c.call(a,$APP.y.h(e,1));case 3:return c.call(a,$APP.y.h(e,1),$APP.y.h(e,2));case 4:return c.call(a,$APP.y.h(e,1),$APP.y.h(e,2),$APP.y.h(e,3));case 5:return c.call(a,$APP.y.h(e,1),$APP.y.h(e,2),$APP.y.h(e,3),$APP.y.h(e,
4));default:return c.apply(a,$APP.YB.g(e).slice(1))}}();if($APP.Be(d))return P8(b,d);if($APP.Le(d))a.pc=l9(d)?function(e,f,h,m,q){return function(){function k(D){var E=null;if(0<arguments.length){E=0;for(var J=Array(arguments.length-0);E<J.length;)J[E]=arguments[E+0],++E;E=new $APP.wd(J,0,null)}return x.call(this,E)}function x(D){return P8(f,$APP.Zg.i($APP.xs,q,D))}k.o=0;k.u=function(D){D=$APP.u(D);return x(D)};k.j=x;return k}()}(a,b,c,null,d):d;else return d}},p9=function(a,b){switch(a instanceof
$APP.sg?a.Ia:null){case "getDefaultProps":throw Error("getDefaultProps not supported");case "getDerivedStateFromProps":return function(c,d){var e=b.call,f=c.argv;null!=f&&(c=$APP.y.i(f,1,null),c=$APP.ze(c)?c:null);return e.call(b,null,c,d)};case "getInitialState":return function(c){var d=c.df;d=null!=d?d:c.df=n9.g(null);return $APP.Hh(d,b.call(c,c))};case "getSnapshotBeforeUpdate":return function(c,d){return b.call(this,this,k9(this,c),d)};case "componentWillReceiveProps":return function(c){return b.call(this,
this,k9(this,c))};case "UNSAFE_componentWillReceiveProps":return function(c){return b.call(this,this,k9(this,c))};case "shouldComponentUpdate":return function(c){var d=o9;if($APP.p(d))return d;d=this.props.argv;var e=c.argv,f=null==d||null==e;if(null==b){if(f)return f;try{return $APP.Qj.h(d,e)}catch(h){return!1}}else return f?b.call(this,this,k9(this,this.props),k9(this,c)):b.call(this,this,d,e)};case "componentWillUpdate":return function(c,d){return b.call(this,this,k9(this,c),d)};case "UNSAFE_componentWillUpdate":return function(c,
d){return b.call(this,this,k9(this,c),d)};case "componentDidUpdate":return function(c,d,e){return b.call(this,this,k9(this,c),d,e)};case "componentWillMount":return function(){return b.call(this,this)};case "UNSAFE_componentWillMount":return function(){return b.call(this,this)};case "componentDidMount":return function(){return b.call(this,this)};case "componentWillUnmount":return function(){var c=$APP.ma(this,"cljsRatom");null!=c&&Z8(c);this.cljsIsDirty=!1;return null==b?null:b.call(this,this)};case "componentDidCatch":return function(c,
d){return b.call(this,this,c,d)};default:return null}},r9=function(a){return $APP.mf(function(b,c,d){return $APP.I.i(b,$APP.Ek.g(q9(c)),d)},$APP.fh,a)},x9=function(a,b){var c=function(){var h=s9.g(a);return $APP.p(h)?h:t9.g(a)}(),d=null==s9.g(a),e=function(){var h=u9.g(a);if($APP.p(h))return h;h=A8(c);return $APP.p(h)?h:$APP.r.g($APP.On.g("reagent"))}(),f=$APP.mf(function(h,m,q){var k=$APP.I.i,x=p9(m,q);return k.call($APP.I,h,m,$APP.p(x)?x:q)},$APP.fh,a);return $APP.I.j(f,u9,e,$APP.be([v9,d,s9,c,
t9,function(){var h=this,m=$APP.ma(h,"cljsRatom");h.cljsIsDirty=!1;return null==m?j9(function(){a:{var q=w9;w9=h;try{var k=m9(h,b);break a}finally{w9=q}k=void 0}return k},h):m._run(!1)}]))},y9=function(a){return $APP.mf(function(b,c,d){c=$APP.ak(c);b[c]=d;return b},{},a)},A9=function(a,b){return x9($APP.Kn.j($APP.be([z9,r9(a)])),b)},E9=function(a,b){function c(m,q,k){import$react.Component.call(this,m,q,k);$APP.p(h)&&(h.h?h.h(this,m):h.call(null,this,m));$APP.p(f)&&(this.state=f.g?f.g(this):f.call(null,
this));this.Yd=B9+=1;return this}a=A9(a,b);b=y9($APP.Zg.j($APP.Ln,a,u9,C9,$APP.Yp,$APP.be([t9,s9,D9])));var d=y9($APP.Rj(a,D9)),e=u9.g(a),f=C9.g(a),h=$APP.Yp.g(a);v8(c.prototype,import$react.Component.prototype,b);$APP.p(t9.g(a))&&(c.prototype.render=t9.g(a));$APP.p(s9.g(a))&&(c.prototype.pc=s9.g(a));$APP.p(v9.g(a))&&(c.prototype.bf=v9.g(a));v8(c,import$react.Component,d);$APP.p(e)&&(c.displayName=e,c.Fc=e,c.Wd=function(m){return $APP.Fc(m,e)});c.pd=!0;return c.prototype.constructor=c},F9=function(a,
b,c){a=N8(a);return b[a]=c},G9=function(a,b){for(;;){var c=b.pc,d=b.argv,e=$APP.Zg.h(c,d);if($APP.Be(e))return P8(a,e);if($APP.Le(e))b.pc=l9(e)?function(f,h,m,q,k,x){return function(){function D(J){var T=null;if(0<arguments.length){T=0;for(var W=Array(arguments.length-0);T<W.length;)W[T]=arguments[T+0],++T;T=new $APP.wd(W,0,null)}return E.call(this,T)}function E(J){return P8(f,$APP.Zg.i($APP.xs,x,J))}D.o=0;D.u=function(J){J=$APP.u(J);return E(J)};D.j=E;return D}()}(a,b,c,null,d,e):e;else return e}},
H9=function(a,b){var c=b.argv,d=b.pc;b=import$react.useState(0);$APP.y.i(b,0,null);var e=$APP.y.i(b,1,null),f=import$react.useRef();$APP.p(f.current)||function(){var m={forceUpdate:function(){return e.g?e.g($APP.Id):e.call(null,$APP.Id)}};m.Yd=B9+=1;m.constructor=d;m.pc=d;return f.current=m}();var h=f.current;b=$APP.ma(h,"cljsRatom");import$react.useEffect(function(){return function(){var m=$APP.ma(h,"cljsRatom");return null==m?null:Z8(m)}},[]);h.argv=c;h.cljsIsDirty=!1;return null==b?j9(function(){a:{var m=
w9;w9=h;try{var q=G9(a,h);break a}finally{w9=m}q=void 0}return q},h):b._run(!1)},I9=function(a,b){a=a.argv;b=b.argv;var c=!1===o9;if(c)try{return $APP.Yd.h(a,b)}catch(d){return!1}else return c},J9=function(a,b){function c(e){return H9(a,e)}var d=$APP.ma(b,N8(a));if($APP.p(d))return d;c.displayName=A8(b);d=import$react.memo(c,I9);F9(a,b,d);return d},N9=function(a,b,c,d){var e=$APP.ah($APP.fh);e=$APP.Te.h(e,K9);if(a===document.activeElement&&$APP.B(L9,a.type)&&"string"===typeof b&&"string"===typeof c){var f=
a.value;if($APP.Qj.h(f,c))return L8.add_after_render(function(){return M9.g?M9.g(d):M9.call(null,d)});c=$APP.Xd(f)-a.selectionStart;c=$APP.Xd(b)-c;d.qd=b;a.value=b;$APP.me(e)&&(e.g?e.g(b):e.call(null,b));a.selectionStart=c;return a.selectionEnd=c}d.qd=b;a.value=b;return $APP.me(e)?e.g?e.g(b):e.call(null,b):null},M9=function(a){if($APP.p(a.Xd)){a.Ae=!1;var b=a.cf,c=a.qd,d=a.$d;return $APP.Qj.h(b,c)?N9(d,b,c,a):null}return null},O9=function(a,b,c){a.qd=c.target.value;$APP.p(a.Ae)||(a.Ae=!0,L8.add_after_render(function(){return M9(a)}));
return b.g?b.g(c):b.call(null,c)},P9=function(a){var b=w9;if($APP.p(function(){var f=null!=a;return f?(f=a.hasOwnProperty("onChange"),$APP.p(f)?a.hasOwnProperty("value"):f):f}())){var c=a.value;c=null==c?"":c;var d=a.onChange,e=a.ref;$APP.p(b.Xd)||(b.Xd=!0,b.qd=c);$APP.p(b.Je)||(b.Je=$APP.me(e)?function(f){b.$d=f;return e.g?e.g(f):e.call(null,f)}:$APP.p($APP.p(e)?e.hasOwnProperty("current"):e)?function(f){b.$d=f;return e.current=f}:function(f){return b.$d=f});b.cf=c;delete a.value;a.defaultValue=
c;a.onChange=function(f){return O9(b,d,f)};a.ref=b.Je}},Q9=function(a,b){return a.hasOwnProperty(b)?$APP.ma(a,b):null},T9=function(a,b,c){if(B8(b)){var d=Q9(R9,$APP.ak(b));null==d?(d=z8(b),b=$APP.ak(b),b=R9[b]=d):b=d}c=S9.g?S9.g(c):S9.call(null,c);a[b]=c;return a},S9=function(a){return"object"!==$APP.ba(a)?a:B8(a)?$APP.ak(a):$APP.ze(a)?$APP.mf(T9,{},a):$APP.se(a)?$APP.Up(a):$APP.Le(a)?function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=
arguments[e+0],++e;e=new $APP.wd(f,0,null)}return c.call(this,e)}function c(d){return $APP.Zg.h(a,d)}b.o=0;b.u=function(d){d=$APP.u(d);return c(d)};b.j=c;return b}():$APP.Up(a)},V9=function(a,b,c){if(B8(b)){var d=Q9(U9,$APP.ak(b));null==d?(d=z8(b),b=$APP.ak(b),b=U9[b]=d):b=d}c=S9(c);a[b]=c;return a},W9=function(a){return"object"!==$APP.ba(a)?a:B8(a)?$APP.ak(a):$APP.ze(a)?$APP.mf(V9,{},a):$APP.se(a)?$APP.Up(a):$APP.Le(a)?function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-
0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.wd(f,0,null)}return c.call(this,e)}function c(d){return $APP.Zg.h(a,d)}b.o=0;b.u=function(d){d=$APP.u(d);return c(d)};b.j=c;return b}():$APP.Up(a)},X9=function(a,b,c,d,e){switch($APP.Xd(b)-e){case 0:return import$react.createElement(c,d);case 1:return import$react.createElement(c,d,P8(a,$APP.y.i(b,e,null)));default:return import$react.createElement.apply(null,$APP.mf(function(f,h,m){h>=e&&f.push(P8(a,m));return f},[c,d],b))}},Y9=function(a,b,c,d){this.tag=
a;this.id=b;this.className=c;this.ef=d},$9=function(a,b,c){var d=$APP.ma(a,N8(c));null==d?l9(a)?a=F9(c,a,a):(d=$APP.A(a),d=$APP.I.i(d,Z9,a),d=E9(d,c),a=F9(c,a,d)):a=d;c={};c.argv=b;b=E8(b);null!=b&&(c.key=b);return import$react.createElement(a,c)},a$=function(a,b,c,d){var e={};e.pc=a;e.argv=$APP.Um.h(b,c);b=E8(b);null!=b&&(e.key=b);return import$react.createElement(J9(d,a),e)},b$=function(a,b,c){var d;if(d=$APP.me(a))d=null==a?null:a.prototype,d=null!=(null==d?null:d.render);return d?$9(a,b,c):a$(a,
b,1,c)},e$=function(a,b){a=Q9(c$,b);if(null==a){var c=$APP.w($APP.mk(d$,$APP.ak(b)));a=$APP.y.i(c,0,null);var d=$APP.y.i(c,1,null);c=$APP.y.i(c,2,null);c=null==c?null:$APP.Om(c,/\./," ");var e=$APP.Qj.h(-1,a.indexOf("-"));a=new Y9(a,d,c,e);return c$[b]=a}return a},i$=function(a,b,c,d){var e=a.tag,f=$APP.y.i(b,c,null),h=null==f||$APP.ze(f),m=function(){var x=h?f:null;var D=$APP.qq.g(x);D=$APP.p(D)?$APP.I.i(x,$APP.qq,f$.g(D)):x;var E=a.id;x=a.className;E=null!=E&&null==$APP.ep.g(D)?$APP.I.i(D,$APP.ep,
E):D;if($APP.p(x)){var J=$APP.I.i,T=f$.h,W=$APP.qq.g(D);D=$APP.p(W)?W:g$.g(D);x=J.call($APP.I,E,$APP.qq,T.call(f$,x,D))}else x=E;x=$APP.p(a.ef)?W9(x):S9(x);return $APP.p(x)?x:{}}();c+=h?1:0;a:switch(e){case "input":case "textarea":var q=!0;break a;default:q=!1}if(q){q=D8(f);var k=function(){var x=d.qf;if($APP.p(x))return x;x=E9(h$,d);return d.qf=x}();return P8(d,$APP.oe(new $APP.G(null,6,5,$APP.H,[k,b,e,m,c,d],null),$APP.Kn.j($APP.be([$APP.p(q)?new $APP.n(null,1,[C8,q],null):null,$APP.A(b)]))))}q=
D8($APP.A(b));null!=q&&(m.key=q);return Q8(d,b,e,m,c)},j$=function(a,b){return $APP.YB.g($APP.Dk.h(function(c){return P8(b,c)},a))},k$=function(a,b,c){null==b&&console.error("vec-to-elem",$APP.dl.j($APP.be([a])));var d=$APP.y.i(a,0,null);switch(d instanceof $APP.sg?d.Ia:null){case "\x3e":return c=$APP.y.i(a,1,null),i$(new Y9(c,null,null,null),a,2,b);case "r\x3e":c=$APP.y.i(a,1,null);d=$APP.y.i(a,2,null);d=$APP.p(d)?d:{};var e=D8($APP.A(a));null!=e&&(d.key=e);return Q8(b,a,c,d,3);case "f\x3e":return a$($APP.y.i(a,
1,null),a,2,b);case "\x3c\x3e":return d=$APP.y.i(a,1,null),c=null==d||$APP.ze(d),d=S9(c?d:null),d=$APP.p(d)?d:{},c=1+(c?1:0),e=E8(a),null!=e&&(d.key=e),Q8(b,a,import$react.Fragment,d,c);default:if(B8(d)||"string"===typeof d)a:for(;;)switch(c=$APP.y.i(a,0,null),d=$APP.ak(c),e=d.indexOf("\x3e"),e){case -1:b=i$(O8(b,d,c),a,1,b);break a;case 0:b=null;break a;default:a=$APP.oe(new $APP.G(null,2,5,$APP.H,[$APP.qk.i(d,0,e),$APP.I.i($APP.oe(a,null),0,$APP.qk.h(d,e+1))],null),$APP.A(a))}else b=c.i?c.i(d,a,
b):c.call(null,d,a,b);return b}},m$=function(a,b,c){var d=o9;o9=!0;try{return import$react_dom.render(a.s?a.s():a.call(null),b,function(){var e=o9;o9=!1;try{return $APP.il.B(l$,$APP.I,b,a),L8.flush_after_render(),null!=c?c.s?c.s():c.call(null):null}finally{o9=e}})}finally{o9=d}},u8="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),C9=new $APP.sg(null,"getInitialState","getInitialState",1541760916),n$=new $APP.sg(null,"component-will-unmount",
"component-will-unmount",-2058314698),s9=new $APP.sg(null,"reagentRender","reagentRender",-358306383),o$=new $APP.t(null,"container","container",-96406180,null),p$=new $APP.t("reagent.core","as-element","reagent.core/as-element",-1369748434,null),q$=new $APP.sg(null,"contextType","contextType",1033066077),r$=new $APP.sg(null,"getDerivedStateFromProps","getDerivedStateFromProps",-991834739),s$=new $APP.sg(null,"display-name","display-name",694513143),g$=new $APP.sg(null,"className","className",-1983287057),
t$=new $APP.sg(null,"parse-tag","parse-tag",1427313738),u$=new $APP.t("reagent.dom","render","reagent.dom/render",-1216356973,null),v$=new $APP.t(null,"callback-or-compiler","callback-or-compiler",90200066,null),w$=new $APP.t(null,"compiler","compiler",1372604796,null),f9=new $APP.sg(null,"on-dispose","on-dispose",2105306360),x$=new $APP.sg(null,"no-cache","no-cache",1588056370),y$=new $APP.sg(null,"function-components","function-components",1492814963),z$=new $APP.sg(null,"callback","callback",-705136228),
v9=new $APP.sg(null,"cljsLegacyRender","cljsLegacyRender",-1527295613),K9=new $APP.sg(null,"on-write","on-write",31519475),A$=new $APP.sg(null,"contextTypes","contextTypes",-2023853910),B$=new $APP.t(null,"render","render",232498073,null),t9=new $APP.sg(null,"render","render",-1408033454),d9=new $APP.sg(null,"auto-run","auto-run",1958400437),C$=new $APP.sg(null,"childContextTypes","childContextTypes",578717991),Z9=new $APP.sg(null,"reagent-render","reagent-render",-985383853),D$=new $APP.t("reagent.core",
"atom","reagent.core/atom",1748890217,null),E$=new $APP.sg(null,"componentWillUnmount","componentWillUnmount",1573788814),F$=new $APP.t(null,"as-element","as-element",-2139409597,null),u9=new $APP.sg(null,"displayName","displayName",-809144601),G$=new $APP.sg(null,"getDerivedStateFromError","getDerivedStateFromError",166658477),e9=new $APP.sg(null,"on-set","on-set",-140953470),H$=new $APP.sg(null,"component-did-update","component-did-update",-1468549173),C8=new $APP.sg(null,"key","key",-1516042587),
I$=new $APP.sg(null,"shouldComponentUpdate","shouldComponentUpdate",1795750960);var J$={};$APP.hl.g(null);var K$={},L$="undefined"!==typeof window&&null!=window.document,y8=new $APP.Tj(null,new $APP.n(null,2,["aria",null,"data",null],null),null),f$=function f$(a){switch(arguments.length){case 0:return f$.s();case 1:return f$.g(arguments[0]);case 2:return f$.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=new $APP.wd(c.slice(2),0,null);return f$.j(arguments[0],arguments[1],c)}};f$.s=function(){return null};
f$.g=function(a){return $APP.se(a)?(a=$APP.sB.h(function(b){return $APP.p(b)?B8(b)?$APP.ak(b):b:null},a),$APP.u(a)?$APP.Br.h(" ",a):null):B8(a)?$APP.ak(a):a};f$.h=function(a,b){return $APP.p(a)?$APP.p(b)?[$APP.r.g(f$.g(a))," ",$APP.r.g(f$.g(b))].join(""):f$.g(a):f$.g(b)};f$.j=function(a,b,c){return $APP.cf.i(f$,f$.h(a,b),c)};f$.u=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);c=$APP.w(c);return this.j(b,a,c)};f$.o=2;var o9=!1;var B9=0,M$=L$?function(){var a=window;return function(){var b=a.requestAnimationFrame;if($APP.p(b))return b;b=a.webkitRequestAnimationFrame;if($APP.p(b))return b;b=a.mozRequestAnimationFrame;if($APP.p(b))return b;b=a.msRequestAnimationFrame;return $APP.p(b)?b:F8}().bind(a)}():F8;$APP.g=K8.prototype;$APP.g.flush_after_render=function(){var a=this.hd;if(null==a)return null;this.hd=null;return I8(a)};$APP.g.queue_render=function(a){null==this.sd&&(this.sd=[]);return J8(this,this.sd,a)};
$APP.g.schedule=function(){function a(){return b.run_queues()}var b=this;if(this.vd)return null;this.vd=!0;return M$.g?M$.g(a):M$.call(null,a)};$APP.g.flush_before_flush=function(){var a=this.jd;if(null==a)return null;this.jd=null;return I8(a)};$APP.g.flush_queues=function(){this.flush_before_flush();H8();this.flush_render();return this.flush_after_render()};$APP.g.run_queues=function(){this.vd=!1;return this.flush_queues()};
$APP.g.add_before_flush=function(a){null==this.jd&&(this.jd=[]);return J8(this,this.jd,a)};$APP.g.add_after_render=function(a){null==this.hd&&(this.hd=[]);return J8(this,this.hd,a)};$APP.g.flush_render=function(){var a=this.sd;if(null==a)return null;this.sd=null;a:{a.sort(G8);for(var b=a.length,c=0;;)if(c<b){var d=a[c];!0===d.cljsIsDirty&&d.forceUpdate();c+=1}else break a}return null};var L8=new K8;var R8;$APP.hl.g(0);var b9=null;$APP.g=Y8.prototype;$APP.g.O=function(a,b,c){return X8(b,c,"RAtom",new $APP.n(null,1,[$APP.xD,this.$a(null)],null))};$APP.g.T=function(){return this.D};$APP.g.X=function(){return $APP.fa(this)};$APP.g.V=function(a,b){return this===b};$APP.g.Ab=function(a,b){a=this.state;this.state=b;null!=this.gb&&W8(this,a,b);return b};$APP.g.Pd=function(a,b){return this.Ab(null,b.g?b.g(this.state):b.call(null,this.state))};
$APP.g.Qd=function(a,b,c){return this.Ab(null,b.h?b.h(this.state,c):b.call(null,this.state,c))};$APP.g.Rd=function(a,b,c,d){return this.Ab(null,b.i?b.i(this.state,c,d):b.call(null,this.state,c,d))};$APP.g.Sd=function(a,b,c,d,e){return this.Ab(null,$APP.Zg.G(b,this.state,c,d,e))};$APP.g.Ud=function(a,b){W8(this,a,b)};$APP.g.nd=function(a,b,c){return U8(this,b,c)};$APP.g.od=function(a,b){return V8(this,b)};$APP.g.Z=function(a,b){return new Y8(this.state,b,this.ge,this.gb)};
$APP.g.$a=function(){T8(this);return this.state};var n9=function n9(a){switch(arguments.length){case 1:return n9.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=new $APP.wd(c.slice(1),0,null);return n9.j(arguments[0],c)}};n9.g=function(a){return new Y8(a,null,null,null)};n9.j=function(a,b){var c=$APP.ah(b);b=$APP.Te.h(c,$APP.ta);c=$APP.Te.h(c,$APP.OC);return new Y8(a,b,c,null)};
n9.u=function(a){var b=$APP.v(a);a=$APP.w(a);return this.j(b,a)};n9.o=1;$APP.g=a9.prototype;$APP.g._peek_at=function(){var a=R8;R8=null;try{return this.$a(null)}finally{R8=a}};$APP.g._handle_change=function(a,b,c){return b===c||this.nc?null:null==this.Mb?(this.nc=!0,null==b9&&(b9=[],!1===L8.vd&&L8.schedule()),b9.push(this)):!0===this.Mb?this._run(!1):this.Mb.g?this.Mb.g(this):this.Mb.call(null,this)};
$APP.g._update_watching=function(a){var b=$APP.Yj(a),c=$APP.Yj(this.yc);this.yc=a;a=$APP.u($APP.n3.h(b,c));for(var d=null,e=0,f=0;;)if(f<e){var h=d.S(null,f);$APP.Jc(h,this,$8);f+=1}else if(a=$APP.u(a))d=a,$APP.Ce(d)?(a=$APP.Uc(d),f=$APP.Vc(d),d=a,e=$APP.Xd(a),a=f):(a=$APP.v(d),$APP.Jc(a,this,$8),a=$APP.w(d),d=null,e=0),f=0;else break;b=$APP.u($APP.n3.h(c,b));c=null;for(e=d=0;;)if(e<d)a=c.S(null,e),$APP.Kc(a,this),e+=1;else if(b=$APP.u(b))c=b,$APP.Ce(c)?(b=$APP.Uc(c),d=$APP.Vc(c),c=b,a=$APP.Xd(b),
b=d,d=a):(a=$APP.v(c),$APP.Kc(a,this),b=$APP.w(c),c=null,d=0),e=0;else return null};$APP.g._queued_run=function(){return this.nc&&null!=this.yc?this._run(!0):null};$APP.g._try_capture=function(a){try{return this.Cd=null,S8(a,this)}catch(b){return this.Cd=this.state=a=b,this.nc=!1}};$APP.g._run=function(a){var b=this.state;a=$APP.p(a)?this._try_capture(this.f):S8(this.f,this);this.Ee||(this.state=a,null==this.gb||$APP.Yd.h(b,a)||W8(this,b,a));return a};
$APP.g._set_opts=function(a){var b=$APP.ah(a);a=$APP.Te.h(b,d9);var c=$APP.Te.h(b,e9),d=$APP.Te.h(b,f9);b=$APP.Te.h(b,x$);null!=a&&(this.Mb=a);null!=c&&(this.lf=c);null!=d&&(this.Fe=d);return null!=b?this.Ee=b:null};$APP.g.O=function(a,b,c){return X8(b,c,"Reaction",new $APP.n(null,1,[$APP.xD,this.$a(null)],null))};$APP.g.X=function(){return $APP.fa(this)};$APP.g.V=function(a,b){return this===b};
$APP.g.ce=function(){var a=this.state,b=this.yc;this.Mb=this.state=this.yc=null;this.nc=!0;b=$APP.u($APP.Yj(b));for(var c=null,d=0,e=0;;)if(e<d){var f=c.S(null,e);$APP.Kc(f,this);e+=1}else if(b=$APP.u(b))c=b,$APP.Ce(c)?(b=$APP.Uc(c),e=$APP.Vc(c),c=b,d=$APP.Xd(b),b=e):(b=$APP.v(c),$APP.Kc(b,this),b=$APP.w(c),c=null,d=0),e=0;else break;null!=this.Fe&&this.Fe(a);a=this.Rf;if(null==a)return null;b=a.length;for(c=0;;)if(c<b)d=a[c],d.g?d.g(this):d.call(null,this),c+=1;else return null};
$APP.g.Ab=function(a,b){a=this.state;this.state=b;this.lf(a,b);W8(this,a,b);return b};$APP.g.Pd=function(a,b){a=this.Ab;var c=this._peek_at();b=b.g?b.g(c):b.call(null,c);return a.call(this,null,b)};$APP.g.Qd=function(a,b,c){a=this.Ab;var d=this._peek_at();b=b.h?b.h(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.g.Rd=function(a,b,c,d){a=this.Ab;var e=this._peek_at();b=b.i?b.i(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};
$APP.g.Sd=function(a,b,c,d,e){return this.Ab(null,$APP.Zg.G(b,this._peek_at(),c,d,e))};$APP.g.Ud=function(a,b){W8(this,a,b)};$APP.g.nd=function(a,b,c){return U8(this,b,c)};$APP.g.od=function(a,b){a=$APP.re(this.gb);V8(this,b);return!a&&$APP.re(this.gb)&&null==this.Mb?this.ce(null):null};
$APP.g.$a=function(){var a=this.Cd;if(null!=a)throw a;(a=null==R8)&&(c9.s?c9.s():c9.call(null));a&&null==this.Mb?this.nc&&(a=this.state,this.state=this.f.s?this.f.s():this.f.call(null),null==this.gb||$APP.Yd.h(a,this.state)||W8(this,a,this.state)):(T8(this),this.nc&&this._run(!1));return this.state};H8=c9;var i9=g9(null);var w9,h9=new $APP.n(null,1,[x$,!0],null),z9=new $APP.n(null,2,[I$,null,E$,null],null),q9=function(a){var b=$APP.hl.g($APP.fh);return function(c){var d=$APP.Te.h($APP.hc(b),c);if(null!=d)return d;d=a.g?a.g(c):a.call(null,c);$APP.il.B(b,$APP.I,c,d);return d}}(function(a){if("string"===typeof a)return a;a=$APP.ak(a);a=$APP.Om(a,/(unsafe|UNSAFE)[-_]/,"UNSAFE_");a=$APP.Wm.h(a,/-/);var b=$APP.u(a);a=$APP.v(b);b=$APP.w(b);return $APP.Zg.i($APP.r,a,$APP.Dk.h(x8,b))}),D9=new $APP.G(null,5,5,$APP.H,[C$,A$,
q$,r$,G$],null);var L9=new $APP.Tj(null,new $APP.n(null,6,["url",null,"tel",null,"text",null,"textarea",null,"password",null,"search",null],null),null),h$=new $APP.n(null,4,[s$,"ReagentInput",H$,M9,n$,function(a){return a.Xd=null},Z9,function(a,b,c,d,e){P9(c);return Q8(e,a,b,c,d)}],null);var N$={},O$,d$=/([^\s\.#]+)(?:#([^\s\.#]+))?(?:\.([^\s#]+))?/,R9={"class":"className","for":"htmlFor",charset:"charSet"},U9={},c$={},P$=function(a){var b=$APP.On.s(),c=$APP.p(y$.g(a))?b$:$9,d=$APP.Te.i(a,t$,e$);if("undefined"===typeof J$||"undefined"===typeof K$||"undefined"===typeof N$||"undefined"===typeof O$)O$=function(e,f,h,m,q){this.mf=e;this.id=f;this.Ce=h;this.ud=m;this.jf=q;this.C=393216;this.J=0},O$.prototype.Z=function(e,f){return new O$(this.mf,this.id,this.Ce,this.ud,f)},O$.prototype.T=
function(){return this.jf},O$.prototype.pf=function(){return this.id},O$.prototype.Ie=function(e,f,h){return this.ud.i?this.ud.i(this,f,h):this.ud.call(null,this,f,h)},O$.prototype.Ge=function(e,f){return"object"!==$APP.ba(f)?f:$APP.Be(f)?k$(f,this,this.Ce):$APP.Ie(f)?j$(f,this):B8(f)?$APP.ak(f):(null!=f?f.C&2147483648||$APP.od===f.ba||(f.C?0:$APP.Xa($APP.Gc,f)):$APP.Xa($APP.Gc,f))?$APP.dl.j($APP.be([f])):f},O$.prototype.He=function(e,f,h,m,q){return X9(this,f,h,m,q)},O$.pd=!0,O$.Fc="reagent.impl.template/t_reagent$impl$template35580",
O$.Wd=function(e){return $APP.Fc(e,"reagent.impl.template/t_reagent$impl$template35580")};return new O$(a,b,c,d,$APP.fh)}($APP.fh);var Q$=function Q$(a){switch(arguments.length){case 1:return Q$.g(arguments[0]);case 2:return Q$.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.r.g(arguments.length)].join(""));}};Q$.g=function(a){return P8(P$,a)};Q$.h=function(a,b){return P8(b,a)};Q$.o=2;
var R$=function R$(a){switch(arguments.length){case 1:return R$.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=new $APP.wd(c.slice(1),0,null);return R$.j(arguments[0],c)}};R$.g=function(a){return n9.g(a)};R$.j=function(a,b){return $APP.Zg.i(n9,a,b)};R$.u=function(a){var b=$APP.v(a);a=$APP.w(a);return this.j(b,a)};R$.o=1;var l$=$APP.hl.g($APP.fh),S$=function S$(a){switch(arguments.length){case 2:return S$.h(arguments[0],arguments[1]);case 3:return S$.i(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.r.g(arguments.length)].join(""));}};S$.h=function(a,b){return S$.i(a,b,P$)};
S$.i=function(a,b,c){c9();c=$APP.me(c)?new $APP.G(null,2,5,$APP.H,[P$,c],null):new $APP.G(null,2,5,$APP.H,[c,z$.g(c)],null);var d=$APP.y.i(c,0,null);c=$APP.y.i(c,1,null);return m$(function(){return P8(d,$APP.me(a)?a.s?a.s():a.call(null):a)},b,c)};S$.o=3;var T$=$APP.io($APP.sP,null),U$=new $APP.n(null,2,[$APP.HV,function(){var a=new $APP.td(function(){return R$},D$,$APP.xj([$APP.S,$APP.O,$APP.So,$APP.Rs,$APP.SI,$APP.Ro,$APP.Qo,$APP.Qs,$APP.X,$APP.Y,$APP.MZ],[$APP.sP,$APP.HV,"reagent/core.cljs",11,new $APP.n(null,6,[$APP.RZ,!0,$APP.Jq,1,$APP.uH,1,$APP.QH,new $APP.G(null,1,5,$APP.H,[new $APP.G(null,1,5,$APP.H,[$APP.PG],null)],null),$APP.X,$APP.N(new $APP.G(null,1,5,$APP.H,[$APP.PG],null),new $APP.G(null,3,5,$APP.H,[$APP.PG,$APP.$l,$APP.FX],null)),$APP.fM,
$APP.N(null,null)],null),1,211,211,$APP.N(new $APP.G(null,1,5,$APP.H,[$APP.PG],null),new $APP.G(null,3,5,$APP.H,[$APP.PG,$APP.$l,$APP.FX],null)),"Like clojure.core/atom, except that it keeps track of derefs.\n  Reagent components that derefs one of these are automatically\n  re-rendered.",$APP.p(R$)?R$.m:null])),b=$APP.hc(a);a=$APP.A(a);var c=T$.l(null),d=$APP.O.g(a);$APP.K.h($APP.r.g(c),$APP.r.g(d));c=new $APP.n(null,4,[$APP.S,T$,$APP.O,d,$APP.X,$APP.X.g(a),$APP.Y,$APP.Y.g(a)],null);return $APP.p($APP.xo.g(a))?
$APP.PB(d,b,c):$APP.p($APP.Xo.g(a))?w8(d,b,c):new $APP.Fo(b,d,c)}(),F$,function(){var a=new $APP.td(function(){return Q$},p$,$APP.xj([$APP.S,$APP.O,$APP.So,$APP.Rs,$APP.SI,$APP.Ro,$APP.Qo,$APP.Qs,$APP.X,$APP.Y,$APP.MZ],[$APP.sP,F$,"reagent/core.cljs",17,new $APP.n(null,6,[$APP.RZ,!1,$APP.Jq,2,$APP.uH,2,$APP.QH,new $APP.G(null,2,5,$APP.H,[new $APP.G(null,1,5,$APP.H,[$APP.ZZ],null),new $APP.G(null,2,5,$APP.H,[$APP.ZZ,w$],null)],null),$APP.X,$APP.N(new $APP.G(null,1,5,$APP.H,[$APP.ZZ],null),new $APP.G(null,
2,5,$APP.H,[$APP.ZZ,w$],null)),$APP.fM,$APP.N(null,null)],null),1,46,46,$APP.N(new $APP.G(null,1,5,$APP.H,[$APP.ZZ],null),new $APP.G(null,2,5,$APP.H,[$APP.ZZ,w$],null)),"Turns a vector of Hiccup syntax into a React element. Returns form\n  unchanged if it is not a vector.",$APP.p(Q$)?Q$.m:null])),b=$APP.hc(a);a=$APP.A(a);var c=T$.l(null),d=$APP.O.g(a);$APP.K.h($APP.r.g(c),$APP.r.g(d));c=new $APP.n(null,4,[$APP.S,T$,$APP.O,d,$APP.X,$APP.X.g(a),$APP.Y,$APP.Y.g(a)],null);return $APP.p($APP.xo.g(a))?
$APP.PB(d,b,c):$APP.p($APP.Xo.g(a))?w8(d,b,c):new $APP.Fo(b,d,c)}()],null),V$=$APP.io($APP.QV,null),W$=new $APP.n(null,1,[B$,function(){var a=new $APP.td(function(){return S$},u$,$APP.xj([$APP.S,$APP.O,$APP.So,$APP.Rs,$APP.SI,$APP.Ro,$APP.Qo,$APP.Qs,$APP.X,$APP.Y,$APP.MZ],[$APP.QV,B$,"reagent/dom.cljs",13,new $APP.n(null,6,[$APP.RZ,!1,$APP.Jq,3,$APP.uH,3,$APP.QH,new $APP.G(null,2,5,$APP.H,[new $APP.G(null,2,5,$APP.H,[$APP.J0,o$],null),new $APP.G(null,3,5,$APP.H,[$APP.J0,o$,v$],null)],null),$APP.X,
$APP.N(new $APP.G(null,2,5,$APP.H,[$APP.J0,o$],null),new $APP.G(null,3,5,$APP.H,[$APP.J0,o$,v$],null)),$APP.fM,$APP.N(null,null)],null),1,29,29,$APP.N(new $APP.G(null,2,5,$APP.H,[$APP.J0,o$],null),new $APP.G(null,3,5,$APP.H,[$APP.J0,o$,v$],null)),"Render a Reagent component into the DOM. The first argument may be\n  either a vector (using Reagent's Hiccup syntax), or a React element.\n  The second argument should be a DOM node.\n\n  Optionally takes a callback that is called when the component is in place.\n\n  Returns the mounted component instance.",
$APP.p(S$)?S$.m:null])),b=$APP.hc(a);a=$APP.A(a);var c=V$.l(null),d=$APP.O.g(a);$APP.K.h($APP.r.g(c),$APP.r.g(d));c=new $APP.n(null,4,[$APP.S,V$,$APP.O,d,$APP.X,$APP.X.g(a),$APP.Y,$APP.Y.g(a)],null);return $APP.p($APP.xo.g(a))?$APP.PB(d,b,c):$APP.p($APP.Xo.g(a))?w8(d,b,c):new $APP.Fo(b,d,c)}()],null);try{$APP.il.i($APP.c8,$APP.TB,new $APP.n(null,1,[$APP.np,new $APP.n(null,2,[$APP.sP,U$,$APP.QV,W$],null)],null))}catch(a){throw console.error("An error occurred when calling (nbb.reagent/init)"),a;};
export { $APP, shadow$provide, $jscomp };
